# Generated by Django 5.1.6 on 2025-09-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique identifier for the service', unique=True)),
                ('name', models.CharField(help_text='Display name of the service', max_length=100)),
                ('description', models.TextField(help_text='Description of what this service does')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('template_workflow_id', models.PositiveIntegerField(help_text='n8n workflow ID of the template')),
                ('credential_type', models.CharField(help_text="n8n credential type (e.g., 'googleOAuth2', 'httpBasicAuth')", max_length=50)),
                ('credential_ui_schema', models.JSONField(help_text='JSON schema for credential input form fields')),
                ('credential_node_types', models.JSONField(help_text='List of n8n node types that use this credential')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is available to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n8n_workflow_id', models.PositiveIntegerField(help_text='n8n workflow ID')),
                ('n8n_credential_id', models.PositiveIntegerField(help_text='n8n credential ID')),
                ('name', models.CharField(help_text='Name of the workflow in n8n', max_length=200)),
                ('active', models.BooleanField(default=False, help_text='Whether this workflow is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workflows', to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'service')},
            },
        ),
    ]
