# Generated by Django 5.1.6 on 2025-09-08 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkflow',
            name='n8n_credential_id',
            field=models.PositiveIntegerField(blank=True, help_text='n8n credential ID', null=True),
        ),
        migrations.AlterField(
            model_name='userworkflow',
            name='n8n_workflow_id',
            field=models.PositiveIntegerField(blank=True, help_text='n8n workflow ID', null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'date'], name='core_transa_phone_n_d2db9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Normalized phone number used as identifier', max_length=20)),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='Monthly budget amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
    ]
