# Generated by Django 5.1.6 on 2025-09-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userworkflow_n8n_credential_id_and_more'),
    ]

    operations = [
    ]
