# Generated by Django 5.2.6 on 2025-09-11 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_seed_ultimate_assistant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(help_text="Long-lived refresh token"),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, help_text="Short-lived access token", null=True
                    ),
                ),
                (
                    "token_expiry",
                    models.DateTimeField(
                        blank=True, help_text="Access token expiry", null=True
                    ),
                ),
                (
                    "scopes",
                    models.TextField(
                        blank=True, help_text="Space-separated OAuth scopes"
                    ),
                ),
                (
                    "gmail_history_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "calendar_channel_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "calendar_resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "calendar_channel_expiration",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "calendar_sync_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
