# Generated by Django 5.2.6 on 2025-09-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_googlecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='credential_node_types',
        ),
        migrations.RemoveField(
            model_name='service',
            name='credential_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='credential_ui_schema',
        ),
        migrations.RemoveField(
            model_name='service',
            name='template_workflow_id',
        ),
    ]
